//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSoap
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class Funcionario : object
    {
        
        private string CedulaField;
        
        private string CodDistribField;
        
        private string CodigoField;
        
        private bool InactivoField;
        
        private string NomDistribField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDistrib
        {
            get
            {
                return this.CodDistribField;
            }
            set
            {
                this.CodDistribField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Inactivo
        {
            get
            {
                return this.InactivoField;
            }
            set
            {
                this.InactivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomDistrib
        {
            get
            {
                return this.NomDistribField;
            }
            set
            {
                this.NomDistribField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Licencia", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class Licencia : object
    {
        
        private int AnoField;
        
        private bool ArriendoField;
        
        private string CodigoField;
        
        private int EjecucionesField;
        
        private string EmpresaField;
        
        private int EquiposField;
        
        private int MesField;
        
        private string ModulosField;
        
        private string ObsField;
        
        private int PdasField;
        
        private int PinField;
        
        private string SerialField;
        
        private System.Nullable<System.DateTime> VenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ano
        {
            get
            {
                return this.AnoField;
            }
            set
            {
                this.AnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Arriendo
        {
            get
            {
                return this.ArriendoField;
            }
            set
            {
                this.ArriendoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ejecuciones
        {
            get
            {
                return this.EjecucionesField;
            }
            set
            {
                this.EjecucionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Equipos
        {
            get
            {
                return this.EquiposField;
            }
            set
            {
                this.EquiposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mes
        {
            get
            {
                return this.MesField;
            }
            set
            {
                this.MesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modulos
        {
            get
            {
                return this.ModulosField;
            }
            set
            {
                this.ModulosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obs
        {
            get
            {
                return this.ObsField;
            }
            set
            {
                this.ObsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pdas
        {
            get
            {
                return this.PdasField;
            }
            set
            {
                this.PdasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                this.PinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Vence
        {
            get
            {
                return this.VenceField;
            }
            set
            {
                this.VenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model.Domain")]
    public partial class Cliente : object
    {
        
        private int AnoContratField;
        
        private System.Nullable<int> AzureIdField;
        
        private bool BuenClienteField;
        
        private string CcRepLegField;
        
        private string CelularField;
        
        private string Celular2Field;
        
        private string CiudadField;
        
        private string ClaseField;
        
        private string CodigoField;
        
        private string ContactoField;
        
        private System.DateTime DateInsertField;
        
        private System.Nullable<System.DateTime> DateUpdateField;
        
        private System.Nullable<decimal> DigVerField;
        
        private string DireccionField;
        
        private string Direccion2Field;
        
        private string DistribuidorIdField;
        
        private string DocPagoComisionField;
        
        private bool DocsField;
        
        private string EmailField;
        
        private string EmailFactField;
        
        private string EmailSop1Field;
        
        private string EmailSop2Field;
        
        private bool EsArriendoField;
        
        private bool EsDemoField;
        
        private bool EsReferidorField;
        
        private bool EsSucursalField;
        
        private bool EscInactivaField;
        
        private string FaxField;
        
        private System.Nullable<System.DateTime> FechaInactivoField;
        
        private System.Nullable<System.DateTime> FechaObsField;
        
        private System.Nullable<System.DateTime> FechaVenLicField;
        
        private System.Nullable<System.DateTime> FpagoComisionField;
        
        private int IdCanalReferidoField;
        
        private System.Nullable<int> IdEgresadoField;
        
        private System.Nullable<int> IdMotivoField;
        
        private System.Nullable<int> IdReferidorField;
        
        private bool InactivoField;
        
        private bool ListaNegraField;
        
        private int MesContratField;
        
        private short NRadicadoField;
        
        private decimal NejeField;
        
        private string NitField;
        
        private bool NoAplicaField;
        
        private bool NoLicenciadoField;
        
        private bool NoViaticosField;
        
        private bool No_SoporteField;
        
        private string NombreField;
        
        private string NombreComercialField;
        
        private string ObsContratoField;
        
        private string ObsInactivoField;
        
        private string ObsLicField;
        
        private string ObsSoporteField;
        
        private string ObservacionField;
        
        private System.Nullable<bool> PdaSuscripField;
        
        private int PinField;
        
        private bool PosiclientField;
        
        private string RazonSocialField;
        
        private string ReferidorIdField;
        
        private string RepLegalField;
        
        private string SerialField;
        
        private bool SinLucroField;
        
        private bool SobreCostoField;
        
        private string SubClasificaField;
        
        private string Suc_deField;
        
        private string TelefonoField;
        
        private string Telefono2Field;
        
        private string TipoClienteField;
        
        private string UserInsertField;
        
        private string UserUpdateField;
        
        private string VenIdField;
        
        private bool VisitaField;
        
        private System.Nullable<decimal> VrPagoComisionField;
        
        private decimal VrViaticoField;
        
        private decimal VrVisitaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnoContrat
        {
            get
            {
                return this.AnoContratField;
            }
            set
            {
                this.AnoContratField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AzureId
        {
            get
            {
                return this.AzureIdField;
            }
            set
            {
                this.AzureIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BuenCliente
        {
            get
            {
                return this.BuenClienteField;
            }
            set
            {
                this.BuenClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcRepLeg
        {
            get
            {
                return this.CcRepLegField;
            }
            set
            {
                this.CcRepLegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular2
        {
            get
            {
                return this.Celular2Field;
            }
            set
            {
                this.Celular2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clase
        {
            get
            {
                return this.ClaseField;
            }
            set
            {
                this.ClaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateInsert
        {
            get
            {
                return this.DateInsertField;
            }
            set
            {
                this.DateInsertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DigVer
        {
            get
            {
                return this.DigVerField;
            }
            set
            {
                this.DigVerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion2
        {
            get
            {
                return this.Direccion2Field;
            }
            set
            {
                this.Direccion2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistribuidorId
        {
            get
            {
                return this.DistribuidorIdField;
            }
            set
            {
                this.DistribuidorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocPagoComision
        {
            get
            {
                return this.DocPagoComisionField;
            }
            set
            {
                this.DocPagoComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Docs
        {
            get
            {
                return this.DocsField;
            }
            set
            {
                this.DocsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFact
        {
            get
            {
                return this.EmailFactField;
            }
            set
            {
                this.EmailFactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailSop1
        {
            get
            {
                return this.EmailSop1Field;
            }
            set
            {
                this.EmailSop1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailSop2
        {
            get
            {
                return this.EmailSop2Field;
            }
            set
            {
                this.EmailSop2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsArriendo
        {
            get
            {
                return this.EsArriendoField;
            }
            set
            {
                this.EsArriendoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsDemo
        {
            get
            {
                return this.EsDemoField;
            }
            set
            {
                this.EsDemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsReferidor
        {
            get
            {
                return this.EsReferidorField;
            }
            set
            {
                this.EsReferidorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsSucursal
        {
            get
            {
                return this.EsSucursalField;
            }
            set
            {
                this.EsSucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EscInactiva
        {
            get
            {
                return this.EscInactivaField;
            }
            set
            {
                this.EscInactivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInactivo
        {
            get
            {
                return this.FechaInactivoField;
            }
            set
            {
                this.FechaInactivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaObs
        {
            get
            {
                return this.FechaObsField;
            }
            set
            {
                this.FechaObsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVenLic
        {
            get
            {
                return this.FechaVenLicField;
            }
            set
            {
                this.FechaVenLicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FpagoComision
        {
            get
            {
                return this.FpagoComisionField;
            }
            set
            {
                this.FpagoComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCanalReferido
        {
            get
            {
                return this.IdCanalReferidoField;
            }
            set
            {
                this.IdCanalReferidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdEgresado
        {
            get
            {
                return this.IdEgresadoField;
            }
            set
            {
                this.IdEgresadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMotivo
        {
            get
            {
                return this.IdMotivoField;
            }
            set
            {
                this.IdMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdReferidor
        {
            get
            {
                return this.IdReferidorField;
            }
            set
            {
                this.IdReferidorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Inactivo
        {
            get
            {
                return this.InactivoField;
            }
            set
            {
                this.InactivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ListaNegra
        {
            get
            {
                return this.ListaNegraField;
            }
            set
            {
                this.ListaNegraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MesContrat
        {
            get
            {
                return this.MesContratField;
            }
            set
            {
                this.MesContratField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NRadicado
        {
            get
            {
                return this.NRadicadoField;
            }
            set
            {
                this.NRadicadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Neje
        {
            get
            {
                return this.NejeField;
            }
            set
            {
                this.NejeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nit
        {
            get
            {
                return this.NitField;
            }
            set
            {
                this.NitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoAplica
        {
            get
            {
                return this.NoAplicaField;
            }
            set
            {
                this.NoAplicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoLicenciado
        {
            get
            {
                return this.NoLicenciadoField;
            }
            set
            {
                this.NoLicenciadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoViaticos
        {
            get
            {
                return this.NoViaticosField;
            }
            set
            {
                this.NoViaticosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool No_Soporte
        {
            get
            {
                return this.No_SoporteField;
            }
            set
            {
                this.No_SoporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial
        {
            get
            {
                return this.NombreComercialField;
            }
            set
            {
                this.NombreComercialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObsContrato
        {
            get
            {
                return this.ObsContratoField;
            }
            set
            {
                this.ObsContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObsInactivo
        {
            get
            {
                return this.ObsInactivoField;
            }
            set
            {
                this.ObsInactivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObsLic
        {
            get
            {
                return this.ObsLicField;
            }
            set
            {
                this.ObsLicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObsSoporte
        {
            get
            {
                return this.ObsSoporteField;
            }
            set
            {
                this.ObsSoporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion
        {
            get
            {
                return this.ObservacionField;
            }
            set
            {
                this.ObservacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> PdaSuscrip
        {
            get
            {
                return this.PdaSuscripField;
            }
            set
            {
                this.PdaSuscripField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                this.PinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Posiclient
        {
            get
            {
                return this.PosiclientField;
            }
            set
            {
                this.PosiclientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferidorId
        {
            get
            {
                return this.ReferidorIdField;
            }
            set
            {
                this.ReferidorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepLegal
        {
            get
            {
                return this.RepLegalField;
            }
            set
            {
                this.RepLegalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SinLucro
        {
            get
            {
                return this.SinLucroField;
            }
            set
            {
                this.SinLucroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SobreCosto
        {
            get
            {
                return this.SobreCostoField;
            }
            set
            {
                this.SobreCostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubClasifica
        {
            get
            {
                return this.SubClasificaField;
            }
            set
            {
                this.SubClasificaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suc_de
        {
            get
            {
                return this.Suc_deField;
            }
            set
            {
                this.Suc_deField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono2
        {
            get
            {
                return this.Telefono2Field;
            }
            set
            {
                this.Telefono2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCliente
        {
            get
            {
                return this.TipoClienteField;
            }
            set
            {
                this.TipoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserInsert
        {
            get
            {
                return this.UserInsertField;
            }
            set
            {
                this.UserInsertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserUpdate
        {
            get
            {
                return this.UserUpdateField;
            }
            set
            {
                this.UserUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenId
        {
            get
            {
                return this.VenIdField;
            }
            set
            {
                this.VenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Visita
        {
            get
            {
                return this.VisitaField;
            }
            set
            {
                this.VisitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VrPagoComision
        {
            get
            {
                return this.VrPagoComisionField;
            }
            set
            {
                this.VrPagoComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VrViatico
        {
            get
            {
                return this.VrViaticoField;
            }
            set
            {
                this.VrViaticoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VrVisita
        {
            get
            {
                return this.VrVisitaField;
            }
            set
            {
                this.VrVisitaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoContrato", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class InfoContrato : object
    {
        
        private bool Es_inicialField;
        
        private System.Nullable<System.DateTime> FinalizaField;
        
        private int Horas_capacitacionField;
        
        private System.Nullable<System.DateTime> IniciaField;
        
        private int No_visitasField;
        
        private string Razon_socialField;
        
        private decimal Vr_cobradoField;
        
        private decimal Vr_pagadoField;
        
        private decimal Vr_sugeridoField;
        
        private string clienteField;
        
        private string distribuidorIDField;
        
        private string nitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Es_inicial
        {
            get
            {
                return this.Es_inicialField;
            }
            set
            {
                this.Es_inicialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Finaliza
        {
            get
            {
                return this.FinalizaField;
            }
            set
            {
                this.FinalizaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Horas_capacitacion
        {
            get
            {
                return this.Horas_capacitacionField;
            }
            set
            {
                this.Horas_capacitacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Inicia
        {
            get
            {
                return this.IniciaField;
            }
            set
            {
                this.IniciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int No_visitas
        {
            get
            {
                return this.No_visitasField;
            }
            set
            {
                this.No_visitasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Razon_social
        {
            get
            {
                return this.Razon_socialField;
            }
            set
            {
                this.Razon_socialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vr_cobrado
        {
            get
            {
                return this.Vr_cobradoField;
            }
            set
            {
                this.Vr_cobradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vr_pagado
        {
            get
            {
                return this.Vr_pagadoField;
            }
            set
            {
                this.Vr_pagadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vr_sugerido
        {
            get
            {
                return this.Vr_sugeridoField;
            }
            set
            {
                this.Vr_sugeridoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distribuidorID
        {
            get
            {
                return this.distribuidorIDField;
            }
            set
            {
                this.distribuidorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Placta", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class Placta : object
    {
        
        private string BaseminimaField;
        
        private string CodigoField;
        
        private string NatField;
        
        private string NombreField;
        
        private System.Nullable<decimal> PorceField;
        
        private byte ReqterField;
        
        private string TipoField;
        
        private string TipoPucField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Baseminima
        {
            get
            {
                return this.BaseminimaField;
            }
            set
            {
                this.BaseminimaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nat
        {
            get
            {
                return this.NatField;
            }
            set
            {
                this.NatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Porce
        {
            get
            {
                return this.PorceField;
            }
            set
            {
                this.PorceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Reqter
        {
            get
            {
                return this.ReqterField;
            }
            set
            {
                this.ReqterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPuc
        {
            get
            {
                return this.TipoPucField;
            }
            set
            {
                this.TipoPucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AyudaGrupo", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class AyudaGrupo : object
    {
        
        private string CodigoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_Unidad", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class tb_Unidad : object
    {
        
        private string CodigoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tb_UNSPSC", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class tb_UNSPSC : object
    {
        
        private string CodigoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AyudaWeb", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class AyudaWeb : object
    {
        
        private string CodGrupField;
        
        private System.Nullable<int> CodigoField;
        
        private string NombreField;
        
        private string TagsField;
        
        private string URLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodGrup
        {
            get
            {
                return this.CodGrupField;
            }
            set
            {
                this.CodGrupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certdig", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class Certdig : object
    {
        
        private string ClienteField;
        
        private string Filepfx64Field;
        
        private string MsgerrorField;
        
        private string NitField;
        
        private bool PerjurField;
        
        private string ResultField;
        
        private string SerialField;
        
        private System.DateTime ValidodesdeField;
        
        private System.DateTime ValidohastaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filepfx64
        {
            get
            {
                return this.Filepfx64Field;
            }
            set
            {
                this.Filepfx64Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nit
        {
            get
            {
                return this.NitField;
            }
            set
            {
                this.NitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Perjur
        {
            get
            {
                return this.PerjurField;
            }
            set
            {
                this.PerjurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Validodesde
        {
            get
            {
                return this.ValidodesdeField;
            }
            set
            {
                this.ValidodesdeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Validohasta
        {
            get
            {
                return this.ValidohastaField;
            }
            set
            {
                this.ValidohastaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contacto", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class Contacto : object
    {
        
        private string ClienteIDField;
        
        private string CodigoField;
        
        private string NombreCliField;
        
        private string NombreConField;
        
        private int PinField;
        
        private string TelefonoField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteID
        {
            get
            {
                return this.ClienteIDField;
            }
            set
            {
                this.ClienteIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCli
        {
            get
            {
                return this.NombreCliField;
            }
            set
            {
                this.NombreCliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCon
        {
            get
            {
                return this.NombreConField;
            }
            set
            {
                this.NombreConField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                this.PinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mciudad", Namespace="http://schemas.datacontract.org/2004/07/TbOnline.Model")]
    public partial class Mciudad : object
    {
        
        private string codigoField;
        
        private string codigoisoField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoiso
        {
            get
            {
                return this.codigoisoField;
            }
            set
            {
                this.codigoisoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsSoap.IWebService")]
    public interface IWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDateTime", ReplyAction="http://tempuri.org/IWebService/GetDateTimeResponse")]
        System.DateTime GetDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDateTime", ReplyAction="http://tempuri.org/IWebService/GetDateTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetDateTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/CheckAccessDB", ReplyAction="http://tempuri.org/IWebService/CheckAccessDBResponse")]
        bool CheckAccessDB(int nroconx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/CheckAccessDB", ReplyAction="http://tempuri.org/IWebService/CheckAccessDBResponse")]
        System.Threading.Tasks.Task<bool> CheckAccessDBAsync(int nroconx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetClave", ReplyAction="http://tempuri.org/IWebService/GetClaveResponse")]
        string GetClave(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetClave", ReplyAction="http://tempuri.org/IWebService/GetClaveResponse")]
        System.Threading.Tasks.Task<string> GetClaveAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Login", ReplyAction="http://tempuri.org/IWebService/LoginResponse")]
        string Login(int nro, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Login", ReplyAction="http://tempuri.org/IWebService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(int nro, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetFuncionario", ReplyAction="http://tempuri.org/IWebService/GetFuncionarioResponse")]
        WsSoap.Funcionario GetFuncionario(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetFuncionario", ReplyAction="http://tempuri.org/IWebService/GetFuncionarioResponse")]
        System.Threading.Tasks.Task<WsSoap.Funcionario> GetFuncionarioAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLicencia", ReplyAction="http://tempuri.org/IWebService/GetLicenciaResponse")]
        WsSoap.Licencia GetLicencia(string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLicencia", ReplyAction="http://tempuri.org/IWebService/GetLicenciaResponse")]
        System.Threading.Tasks.Task<WsSoap.Licencia> GetLicenciaAsync(string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLicenciaByPin", ReplyAction="http://tempuri.org/IWebService/GetLicenciaByPinResponse")]
        WsSoap.Licencia GetLicenciaByPin(int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLicenciaByPin", ReplyAction="http://tempuri.org/IWebService/GetLicenciaByPinResponse")]
        System.Threading.Tasks.Task<WsSoap.Licencia> GetLicenciaByPinAsync(int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCliente", ReplyAction="http://tempuri.org/IWebService/GetClienteResponse")]
        WsSoap.Cliente GetCliente(string nit, string idDistrib);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCliente", ReplyAction="http://tempuri.org/IWebService/GetClienteResponse")]
        System.Threading.Tasks.Task<WsSoap.Cliente> GetClienteAsync(string nit, string idDistrib);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Auth", ReplyAction="http://tempuri.org/IWebService/AuthResponse")]
        WsSoap.Cliente Auth(int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Auth", ReplyAction="http://tempuri.org/IWebService/AuthResponse")]
        System.Threading.Tasks.Task<WsSoap.Cliente> AuthAsync(int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetInfoContrato", ReplyAction="http://tempuri.org/IWebService/GetInfoContratoResponse")]
        WsSoap.InfoContrato GetInfoContrato(string nit, string idDistrib, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetInfoContrato", ReplyAction="http://tempuri.org/IWebService/GetInfoContratoResponse")]
        System.Threading.Tasks.Task<WsSoap.InfoContrato> GetInfoContratoAsync(string nit, string idDistrib, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetPlactas", ReplyAction="http://tempuri.org/IWebService/GetPlactasResponse")]
        WsSoap.Placta[] GetPlactas(string tipoPuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetPlactas", ReplyAction="http://tempuri.org/IWebService/GetPlactasResponse")]
        System.Threading.Tasks.Task<WsSoap.Placta[]> GetPlactasAsync(string tipoPuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutIdredmaq", ReplyAction="http://tempuri.org/IWebService/PutIdredmaqResponse")]
        int PutIdredmaq(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutIdredmaq", ReplyAction="http://tempuri.org/IWebService/PutIdredmaqResponse")]
        System.Threading.Tasks.Task<int> PutIdredmaqAsync(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutIdredmaq2", ReplyAction="http://tempuri.org/IWebService/PutIdredmaq2Response")]
        int PutIdredmaq2(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha, string id_instala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutIdredmaq2", ReplyAction="http://tempuri.org/IWebService/PutIdredmaq2Response")]
        System.Threading.Tasks.Task<int> PutIdredmaq2Async(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha, string id_instala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutVisos", ReplyAction="http://tempuri.org/IWebService/PutVisosResponse")]
        int PutVisos(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutVisos", ReplyAction="http://tempuri.org/IWebService/PutVisosResponse")]
        System.Threading.Tasks.Task<int> PutVisosAsync(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutVisos2", ReplyAction="http://tempuri.org/IWebService/PutVisos2Response")]
        int PutVisos2(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps, 
                    string id_instala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PutVisos2", ReplyAction="http://tempuri.org/IWebService/PutVisos2Response")]
        System.Threading.Tasks.Task<int> PutVisos2Async(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps, 
                    string id_instala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetAyudaGrupo", ReplyAction="http://tempuri.org/IWebService/GetAyudaGrupoResponse")]
        WsSoap.AyudaGrupo[] GetAyudaGrupo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetAyudaGrupo", ReplyAction="http://tempuri.org/IWebService/GetAyudaGrupoResponse")]
        System.Threading.Tasks.Task<WsSoap.AyudaGrupo[]> GetAyudaGrupoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUnidades", ReplyAction="http://tempuri.org/IWebService/GetUnidadesResponse")]
        WsSoap.tb_Unidad[] GetUnidades(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUnidades", ReplyAction="http://tempuri.org/IWebService/GetUnidadesResponse")]
        System.Threading.Tasks.Task<WsSoap.tb_Unidad[]> GetUnidadesAsync(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUNSPSC", ReplyAction="http://tempuri.org/IWebService/GetUNSPSCResponse")]
        WsSoap.tb_UNSPSC[] GetUNSPSC(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUNSPSC", ReplyAction="http://tempuri.org/IWebService/GetUNSPSCResponse")]
        System.Threading.Tasks.Task<WsSoap.tb_UNSPSC[]> GetUNSPSCAsync(string cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetAyudaWeb", ReplyAction="http://tempuri.org/IWebService/GetAyudaWebResponse")]
        WsSoap.AyudaWeb[] GetAyudaWeb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetAyudaWeb", ReplyAction="http://tempuri.org/IWebService/GetAyudaWebResponse")]
        System.Threading.Tasks.Task<WsSoap.AyudaWeb[]> GetAyudaWebAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCertdig", ReplyAction="http://tempuri.org/IWebService/GetCertdigResponse")]
        WsSoap.Certdig GetCertdig(string nit, string serial, int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCertdig", ReplyAction="http://tempuri.org/IWebService/GetCertdigResponse")]
        System.Threading.Tasks.Task<WsSoap.Certdig> GetCertdigAsync(string nit, string serial, int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCertdigPT", ReplyAction="http://tempuri.org/IWebService/GetCertdigPTResponse")]
        WsSoap.Certdig GetCertdigPT(string nit, int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCertdigPT", ReplyAction="http://tempuri.org/IWebService/GetCertdigPTResponse")]
        System.Threading.Tasks.Task<WsSoap.Certdig> GetCertdigPTAsync(string nit, int pin, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetContactosPBX", ReplyAction="http://tempuri.org/IWebService/GetContactosPBXResponse")]
        WsSoap.Contacto[] GetContactosPBX();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetContactosPBX", ReplyAction="http://tempuri.org/IWebService/GetContactosPBXResponse")]
        System.Threading.Tasks.Task<WsSoap.Contacto[]> GetContactosPBXAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCiudad", ReplyAction="http://tempuri.org/IWebService/GetCiudadResponse")]
        WsSoap.Mciudad[] GetCiudad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCiudad", ReplyAction="http://tempuri.org/IWebService/GetCiudadResponse")]
        System.Threading.Tasks.Task<WsSoap.Mciudad[]> GetCiudadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDpto", ReplyAction="http://tempuri.org/IWebService/GetDptoResponse")]
        WsSoap.Mciudad[] GetDpto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetDpto", ReplyAction="http://tempuri.org/IWebService/GetDptoResponse")]
        System.Threading.Tasks.Task<WsSoap.Mciudad[]> GetDptoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWebServiceChannel : WsSoap.IWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<WsSoap.IWebService>, WsSoap.IWebService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        // Construct 0 Args
        public WebServiceClient() 
        { }

        public WebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), WebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.DateTime GetDateTime()
        {
            return base.Channel.GetDateTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetDateTimeAsync()
        {
            return base.Channel.GetDateTimeAsync();
        }
        
        public bool CheckAccessDB(int nroconx)
        {
            return base.Channel.CheckAccessDB(nroconx);
        }
        
        public System.Threading.Tasks.Task<bool> CheckAccessDBAsync(int nroconx)
        {
            return base.Channel.CheckAccessDBAsync(nroconx);
        }
        
        public string GetClave(string codigo)
        {
            return base.Channel.GetClave(codigo);
        }
        
        public System.Threading.Tasks.Task<string> GetClaveAsync(string codigo)
        {
            return base.Channel.GetClaveAsync(codigo);
        }
        
        public string Login(int nro, string clave)
        {
            return base.Channel.Login(nro, clave);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(int nro, string clave)
        {
            return base.Channel.LoginAsync(nro, clave);
        }
        
        public WsSoap.Funcionario GetFuncionario(string codigo)
        {
            return base.Channel.GetFuncionario(codigo);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Funcionario> GetFuncionarioAsync(string codigo)
        {
            return base.Channel.GetFuncionarioAsync(codigo);
        }
        
        public WsSoap.Licencia GetLicencia(string serial)
        {
            return base.Channel.GetLicencia(serial);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Licencia> GetLicenciaAsync(string serial)
        {
            return base.Channel.GetLicenciaAsync(serial);
        }
        
        public WsSoap.Licencia GetLicenciaByPin(int pin, string token)
        {
            return base.Channel.GetLicenciaByPin(pin, token);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Licencia> GetLicenciaByPinAsync(int pin, string token)
        {
            return base.Channel.GetLicenciaByPinAsync(pin, token);
        }
        
        public WsSoap.Cliente GetCliente(string nit, string idDistrib)
        {
            return base.Channel.GetCliente(nit, idDistrib);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Cliente> GetClienteAsync(string nit, string idDistrib)
        {
            return base.Channel.GetClienteAsync(nit, idDistrib);
        }
        
        public WsSoap.Cliente Auth(int pin, string token)
        {
            return base.Channel.Auth(pin, token);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Cliente> AuthAsync(int pin, string token)
        {
            return base.Channel.AuthAsync(pin, token);
        }
        
        public WsSoap.InfoContrato GetInfoContrato(string nit, string idDistrib, string clave)
        {
            return base.Channel.GetInfoContrato(nit, idDistrib, clave);
        }
        
        public System.Threading.Tasks.Task<WsSoap.InfoContrato> GetInfoContratoAsync(string nit, string idDistrib, string clave)
        {
            return base.Channel.GetInfoContratoAsync(nit, idDistrib, clave);
        }
        
        public WsSoap.Placta[] GetPlactas(string tipoPuc)
        {
            return base.Channel.GetPlactas(tipoPuc);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Placta[]> GetPlactasAsync(string tipoPuc)
        {
            return base.Channel.GetPlactasAsync(tipoPuc);
        }
        
        public int PutIdredmaq(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha)
        {
            return base.Channel.PutIdredmaq(cliente, pcname, username, clientname, serialhd, ip, fecha);
        }
        
        public System.Threading.Tasks.Task<int> PutIdredmaqAsync(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha)
        {
            return base.Channel.PutIdredmaqAsync(cliente, pcname, username, clientname, serialhd, ip, fecha);
        }
        
        public int PutIdredmaq2(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha, string id_instala)
        {
            return base.Channel.PutIdredmaq2(cliente, pcname, username, clientname, serialhd, ip, fecha, id_instala);
        }
        
        public System.Threading.Tasks.Task<int> PutIdredmaq2Async(string cliente, string pcname, string username, string clientname, decimal serialhd, string ip, System.DateTime fecha, string id_instala)
        {
            return base.Channel.PutIdredmaq2Async(cliente, pcname, username, clientname, serialhd, ip, fecha, id_instala);
        }
        
        public int PutVisos(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps)
        {
            return base.Channel.PutVisos(Tipo, Cliente, Serial, NombreLic, ActivaLic, NombreEmp, NombrecEmp, Nit, RepLegal, DirTel, Contador, RevFiscal, CodApp, Version, FechaExe, NoEjecu, Usuario, NomPc, NomUserPC, NroUsrSop, ErrorNo, ErrorMsj, ErrorProc, ErrorStack, VisoInfo, InfoAllEmps);
        }
        
        public System.Threading.Tasks.Task<int> PutVisosAsync(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps)
        {
            return base.Channel.PutVisosAsync(Tipo, Cliente, Serial, NombreLic, ActivaLic, NombreEmp, NombrecEmp, Nit, RepLegal, DirTel, Contador, RevFiscal, CodApp, Version, FechaExe, NoEjecu, Usuario, NomPc, NomUserPC, NroUsrSop, ErrorNo, ErrorMsj, ErrorProc, ErrorStack, VisoInfo, InfoAllEmps);
        }
        
        public int PutVisos2(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps, 
                    string id_instala)
        {
            return base.Channel.PutVisos2(Tipo, Cliente, Serial, NombreLic, ActivaLic, NombreEmp, NombrecEmp, Nit, RepLegal, DirTel, Contador, RevFiscal, CodApp, Version, FechaExe, NoEjecu, Usuario, NomPc, NomUserPC, NroUsrSop, ErrorNo, ErrorMsj, ErrorProc, ErrorStack, VisoInfo, InfoAllEmps, id_instala);
        }
        
        public System.Threading.Tasks.Task<int> PutVisos2Async(
                    string Tipo, 
                    string Cliente, 
                    string Serial, 
                    string NombreLic, 
                    System.Nullable<bool> ActivaLic, 
                    string NombreEmp, 
                    string NombrecEmp, 
                    string Nit, 
                    string RepLegal, 
                    string DirTel, 
                    string Contador, 
                    string RevFiscal, 
                    string CodApp, 
                    string Version, 
                    System.Nullable<System.DateTime> FechaExe, 
                    System.Nullable<int> NoEjecu, 
                    string Usuario, 
                    string NomPc, 
                    string NomUserPC, 
                    System.Nullable<int> NroUsrSop, 
                    System.Nullable<int> ErrorNo, 
                    string ErrorMsj, 
                    string ErrorProc, 
                    string ErrorStack, 
                    string VisoInfo, 
                    string InfoAllEmps, 
                    string id_instala)
        {
            return base.Channel.PutVisos2Async(Tipo, Cliente, Serial, NombreLic, ActivaLic, NombreEmp, NombrecEmp, Nit, RepLegal, DirTel, Contador, RevFiscal, CodApp, Version, FechaExe, NoEjecu, Usuario, NomPc, NomUserPC, NroUsrSop, ErrorNo, ErrorMsj, ErrorProc, ErrorStack, VisoInfo, InfoAllEmps, id_instala);
        }
        
        public WsSoap.AyudaGrupo[] GetAyudaGrupo()
        {
            return base.Channel.GetAyudaGrupo();
        }
        
        public System.Threading.Tasks.Task<WsSoap.AyudaGrupo[]> GetAyudaGrupoAsync()
        {
            return base.Channel.GetAyudaGrupoAsync();
        }
        
        public WsSoap.tb_Unidad[] GetUnidades(string cod)
        {
            return base.Channel.GetUnidades(cod);
        }
        
        public System.Threading.Tasks.Task<WsSoap.tb_Unidad[]> GetUnidadesAsync(string cod)
        {
            return base.Channel.GetUnidadesAsync(cod);
        }
        
        public WsSoap.tb_UNSPSC[] GetUNSPSC(string cod)
        {
            return base.Channel.GetUNSPSC(cod);
        }
        
        public System.Threading.Tasks.Task<WsSoap.tb_UNSPSC[]> GetUNSPSCAsync(string cod)
        {
            return base.Channel.GetUNSPSCAsync(cod);
        }
        
        public WsSoap.AyudaWeb[] GetAyudaWeb()
        {
            return base.Channel.GetAyudaWeb();
        }
        
        public System.Threading.Tasks.Task<WsSoap.AyudaWeb[]> GetAyudaWebAsync()
        {
            return base.Channel.GetAyudaWebAsync();
        }
        
        public WsSoap.Certdig GetCertdig(string nit, string serial, int pin, string token)
        {
            return base.Channel.GetCertdig(nit, serial, pin, token);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Certdig> GetCertdigAsync(string nit, string serial, int pin, string token)
        {
            return base.Channel.GetCertdigAsync(nit, serial, pin, token);
        }
        
        public WsSoap.Certdig GetCertdigPT(string nit, int pin, string token)
        {
            return base.Channel.GetCertdigPT(nit, pin, token);
        }
        
        public System.Threading.Tasks.Task<WsSoap.Certdig> GetCertdigPTAsync(string nit, int pin, string token)
        {
            return base.Channel.GetCertdigPTAsync(nit, pin, token);
        }
        
        public WsSoap.Contacto[] GetContactosPBX()
        {
            return base.Channel.GetContactosPBX();
        }
        
        public System.Threading.Tasks.Task<WsSoap.Contacto[]> GetContactosPBXAsync()
        {
            return base.Channel.GetContactosPBXAsync();
        }
        
        public WsSoap.Mciudad[] GetCiudad()
        {
            return base.Channel.GetCiudad();
        }
        
        public System.Threading.Tasks.Task<WsSoap.Mciudad[]> GetCiudadAsync()
        {
            return base.Channel.GetCiudadAsync();
        }
        
        public WsSoap.Mciudad[] GetDpto()
        {
            return base.Channel.GetDpto();
        }
        
        public System.Threading.Tasks.Task<WsSoap.Mciudad[]> GetDptoAsync()
        {
            return base.Channel.GetDptoAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://tbonline-webapp.azurewebsites.net/WebService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWebService))
            {
                return new System.ServiceModel.EndpointAddress("https://tbonline-webapp.azurewebsites.net/WebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWebService,
            
            BasicHttpsBinding_IWebService,
        }
    }
}
